language: node_js
sudo: false
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
before_install:
  - wget http://dl.4players.de/ts/releases/3.0.13.8/teamspeak3-server_linux_amd64-3.0.13.8.tar.bz2
  - tar xjvf teamspeak3-server_linux_amd64-3.0.13.8.tar.bz2
  - chmod +x teamspeak3-server_linux_amd64/ts3server_minimal_runscript.sh
  - nohup ./teamspeak3-server_linux_amd64/ts3server_minimal_runscript.sh serveradmin_password=fernand &
script: "npm test"
